part1:
	gcc -o part1 IERG2080_1155176283_part1.c

part2:
	gcc -o part2 IERG2080_1155xxxxxx_part2.c

part3:
	gcc -o part3 IERG2080_1155xxxxxx_part3.c

part4:
	gcc -o part4 IERG2080_1155xxxxxx_part4.c -pthread

